baseURL = 'http://www.face.ubiobio.cl/~jfuentes/classes/hc/'
languageCode = 'en-us'
title = 'Heterogeneous Computing'
theme = 'kitab'

disableKinds = ["taxonomy", "taxonomyTerm"]
pluralizelisttitles = false

[params]
  author = "Joel Fuentes"
  description = "Programming Heterogeneous Arquitectures using Data Parallel C++"
  dateFormat = "2006-01-02"
  footer1 = "Universidad del Bío-Bío, Chile"
  footer2 = "2021"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true